export type Scroll = {
  id: string;
  rank: "A" | "B" | "C";
  name: string;
  description: string;
  type: "flat" | "percentage";
  stat: string;
  value: number;
  quantity: number;
};

export const scrollList: Scroll[] = [
  // RANK A
  {
    id: "dano-%-a",
    rank: "A",
    name: "Scroll de Dano % A",
    description: "Buff de Dano + 6%",
    type: "percentage",
    stat: "damage",
    value: 0.06,
    quantity: 0,
  },
  {
    id: "dano-#-a",
    rank: "A",
    name: "Scroll de Dano # A",
    description: "Buff de Dano + 5",
    type: "flat",
    stat: "damage",
    value: 5,
    quantity: 0,
  },

  {
    id: "defesa-%-a",
    rank: "A",
    name: "Scroll de Defesa % A",
    description: "Buff de Defesa + 20%",
    type: "percentage",
    stat: "defense",
    value: 0.2,
    quantity: 0,
  },
  {
    id: "defesa-#-a",
    rank: "A",
    name: "Scroll de Defesa # A",
    description: "Buff de Defesa + 6",
    type: "flat",
    stat: "defense",
    value: 6,
    quantity: 0,
  },
  {
    id: "hp-regen-a",
    rank: "A",
    name: "Scroll de HP Regen",
    description: "Buff de HP Regen + 0.1%",
    type: "percentage",
    stat: "hpRegen",
    value: 0.1,
    quantity: 0,
  },
  {
    id: "ck-regen-a",
    rank: "A",
    name: "Scroll de CK Regen",
    description: "Buff de CK Regen + 0.1%",
    type: "percentage",
    stat: "chakraRegen",
    value: 0.1,
    quantity: 0,
  },
  {
    id: "vida-%-a",
    rank: "A",
    name: "Scroll de Vida %",
    description: "Buff de Vida + 6%",
    type: "percentage",
    stat: "hp",
    value: 0.06,
    quantity: 0,
  },
  {
    id: "vida-#-a",
    rank: "A",
    name: "Scroll de Vida #",
    description: "Buff de Vida + 150",
    type: "flat",
    stat: "hp",
    value: 150,
    quantity: 0,
  },
  {
    id: "chakra-%-a",
    rank: "A",
    name: "Scroll de Chakra %",
    description: "Buff de Chakra + 6%",
    type: "percentage",
    stat: "chakra",
    value: 0.06,
    quantity: 0,
  },
  {
    id: "chakra-#-a",
    rank: "A",
    name: "Scroll de Chakra #",
    description: "Buff de Chakra 270",
    type: "flat",
    stat: "chakra",
    value: 270,
    quantity: 0,
  },

  {
    id: "cdr-a",
    rank: "A",
    name: "Scroll de CDR A",
    description: "Buff de CDR + 3%",
    type: "percentage",
    stat: "cdr",
    value: 3,
    quantity: 0,
  },

  {
    id: "pen-%-a",
    rank: "A",
    name: "Scroll de Penetração % A",
    description: "Buff de Penetração de Defesa + 20%",
    type: "percentage",
    stat: "defensePenetration",
    value: 0.2,
    quantity: 0,
  },
  {
    id: "pen-#-a",
    rank: "A",
    name: "Scroll de Penetração # A",
    description: "Buff de Penetração de Defesa + 6",
    type: "flat",
    stat: "defensePenetration",
    value: 6,
    quantity: 0,
  },

  {
    id: "crit-chance-a",
    rank: "A",
    name: "Scroll de Chance Crítico A",
    description: "Buff de Chance Crítico + 5%",
    type: "percentage",
    stat: "criticalChance",
    value: 5,
    quantity: 0,
  },
  {
    id: "crit-dmg-a",
    rank: "A",
    name: "Scroll de Dano Crítico A",
    description: "Buff de Dano Crítico + 5%",
    type: "percentage",
    stat: "criticalDamage",
    value: 5,
    quantity: 0,
  },
  {
    id: "crit-red-a",
    rank: "A",
    name: "Scroll de Redução de Crítico A",
    description: "Buff de Redução de Crítico + 5%",
    type: "percentage",
    stat: "criticalReduction",
    value: 5,
    quantity: 0,
  },
  {
    id: "evasion-a",
    rank: "A",
    name: "Scroll de Esquiva A",
    description: "Buff de Esquiva + 5%",
    type: "percentage",
    stat: "evasion",
    value: 5,
    quantity: 0,
  },

  // RANK B

  {
    id: "dano-%-b",
    rank: "B",
    name: "Scroll de Dano % B",
    description: "Buff de Dano + 4%",
    type: "percentage",
    stat: "damage",
    value: 0.04,
    quantity: 0,
  },
  {
    id: "dano-#-b",
    rank: "B",
    name: "Scroll de Dano # B",
    description: "Buff de Dano + 3",
    type: "flat",
    stat: "damage",
    value: 3,
    quantity: 0,
  },
  {
    id: "defesa-%-b",
    rank: "B",
    name: "Scroll de Defesa % B",
    description: "Buff de Defesa + 15%",
    type: "percentage",
    stat: "defense",
    value: 0.15,
    quantity: 0,
  },
  {
    id: "defesa-#-b",
    rank: "B",
    name: "Scroll de Defesa # B",
    description: "Buff de Defesa + 4",
    type: "flat",
    stat: "defense",
    value: 4,
    quantity: 0,
  },
  {
    id: "vida-%-b",
    rank: "B",
    name: "Scroll de Vida % B",
    description: "Buff de Vida + 4%",
    type: "percentage",
    stat: "hp",
    value: 0.04,
    quantity: 0,
  },
  {
    id: "vida-#-b",
    rank: "B",
    name: "Scroll de Vida # B",
    description: "Buff de Vida + 100",
    type: "flat",
    stat: "hp",
    value: 100,
    quantity: 0,
  },
  {
    id: "chakra-%-b",
    rank: "B",
    name: "Scroll de Chakra % B",
    description: "Buff de Chakra + 4%",
    type: "percentage",
    stat: "chakra",
    value: 0.04,
    quantity: 0,
  },
  {
    id: "chakra-#-b",
    rank: "B",
    name: "Scroll de Chakra # B",
    description: "Buff de Chakra + 180",
    type: "flat",
    stat: "chakra",
    value: 180,
    quantity: 0,
  },
  {
    id: "cdr-b",
    rank: "B",
    name: "Scroll de CDR B",
    description: "Buff de CDR + 2%",
    type: "percentage",
    stat: "cdr",
    value: 2,
    quantity: 0,
  },
  {
    id: "pen-%-b",
    rank: "B",
    name: "Scroll de Penetração % B",
    description: "Buff de Penetração de Defesa + 15%",
    type: "percentage",
    stat: "defensePenetration",
    value: 0.15,
    quantity: 0,
  },
  {
    id: "pen-#-b",
    rank: "B",
    name: "Scroll de Penetração # B",
    description: "Buff de Penetração de Defesa + 4",
    type: "flat",
    stat: "defensePenetration",
    value: 4,
    quantity: 0,
  },

  {
    id: "crit-chance-b",
    rank: "B",
    name: "Scroll de Chance Crítico B",
    description: "Buff de Chance Crítico + 3%",
    type: "percentage",
    stat: "criticalChance",
    value: 3,
    quantity: 0,
  },
  {
    id: "crit-dmg-b",
    rank: "B",
    name: "Scroll de Dano Crítico B",
    description: "Buff de Dano Crítico + 3%",
    type: "percentage",
    stat: "criticalDamage",
    value: 3,
    quantity: 0,
  },
  {
    id: "crit-red-b",
    rank: "B",
    name: "Scroll de Redução de Crítico B",
    description: "Buff de Redução de Crítico + 3%",
    type: "percentage",
    stat: "criticalReduction",
    value: 3,
    quantity: 0,
  },
  {
    id: "evasion-b",
    rank: "B",
    name: "Scroll de Esquiva B",
    description: "Buff de Esquiva + 3%",
    type: "percentage",
    stat: "evasion",
    value: 3,
    quantity: 0,
  },
  {
    id: "dano-%-c",
    name: "Scroll de Dano % C",
    description: "Buff de Dano + 2%",
    type: "percentage",
    stat: "damage",
    value: 0.02,
    quantity: 0,
    rank: "C",
  },
  {
    id: "dano-#-c",
    name: "Scroll de Dano # C",
    description: "Buff de Dano + 1",
    type: "flat",
    stat: "damage",
    value: 1,
    quantity: 0,
    rank: "C",
  },
  {
    id: "defesa-%-c",
    name: "Scroll de Defesa % C",
    description: "Buff de Defesa + 7%",
    type: "percentage",
    stat: "defense",
    value: 0.07,
    quantity: 0,
    rank: "C",
  },
  {
    id: "defesa-#-c",
    name: "Scroll de Defesa # C",
    description: "Buff de Defesa + 2",
    type: "flat",
    stat: "defense",
    value: 2,
    quantity: 0,
    rank: "C",
  },
  {
    id: "vida-%-c",
    name: "Scroll de Vida % C",
    description: "Buff de Vida + 2%",
    type: "percentage",
    stat: "hp",
    value: 0.02,
    quantity: 0,
    rank: "C",
  },
  {
    id: "vida-#-c",
    name: "Scroll de Vida # C",
    description: "Buff de Vida + 50",
    type: "flat",
    stat: "hp",
    value: 50,
    quantity: 0,
    rank: "C",
  },

  {
    id: "chakra-%-c",
    name: "Scroll de Chakra % C",
    description: "Buff de Chakra + 2%",
    type: "percentage",
    stat: "chakra",
    value: 0.02,
    quantity: 0,
    rank: "C",
  },
  {
    id: "chakra-#-c",
    name: "Scroll de Chakra # C",
    description: "Buff de Chakra + 90",
    type: "flat",
    stat: "chakra",
    value: 90,
    quantity: 0,
    rank: "C",
  },

  {
    id: "cdr-c",
    name: "Scroll de CDR C",
    description: "Buff de CDR + 1%",
    type: "percentage",
    stat: "cdr",
    value: 1,
    quantity: 0,
    rank: "C",
  },

  {
    id: "pen-%-c",
    name: "Scroll de Penetração % C",
    description: "Buff de Penetração de Defesa + 7%",
    type: "percentage",
    stat: "defensePenetration",
    value: 0.07,
    quantity: 0,
    rank: "C",
  },
  {
    id: "pen-#-c",
    name: "Scroll de Penetração # C",
    description: "Buff de Penetração de Defesa + 2",
    type: "flat",
    stat: "defensePenetration",
    value: 2,
    quantity: 0,
    rank: "C",
  },

  {
    id: "crit-chance-c",
    name: "Scroll de Chance Crítico C",
    description: "Buff de Chance Crítico + 1%",
    type: "percentage",
    stat: "criticalChance",
    value: 1,
    quantity: 0,
    rank: "C",
  },
  {
    id: "crit-dmg-c",
    name: "Scroll de Dano Crítico C",
    description: "Buff de Dano Crítico + 1%",
    type: "percentage",
    stat: "criticalDamage",
    value: 1,
    quantity: 0,
    rank: "C",
  },
  {
    id: "crit-red-c",
    name: "Scroll de Redução de Crítico C",
    description: "Buff de Redução de Crítico + 5%", // ← valor da lista original (parece ter sido 51% por engano?)
    type: "percentage",
    stat: "criticalReduction",
    value: 2,
    quantity: 0,
    rank: "C",
  },
  {
    id: "evasion-c",
    name: "Scroll de Esquiva C",
    description: "Buff de Esquiva + 1%",
    type: "percentage",
    stat: "evasion",
    value: 1,
    quantity: 0,
    rank: "C",
  },
];
